// Auto-generated. Total: 129 questions + 2 authored.
const QUESTIONS = [
  { "id": "s1q1", "subject": 1, "number": 1, "question": "某電商企業希望利用自然語言處理（NLP）技術，分析顧客在社群平 台與商品評論中的文字內容，以即時掌握顧客對產品的滿意度變化。 若採用情感分析（Sentiment Analysis）模型，其主要目的為何？", "options": { "A": "預測顧客使用的語言風格與語氣", "B": "判斷文本中所表達的情感傾向", "C": "將顧客留言自動翻譯成企業內部指定語言", "D": "產生顧客評論的自動化摘要內容" }, "answer": "B", "topic": "NLP" },
  { "id": "s1q2", "subject": 1, "number": 2, "question": "某跨國金融科技公司導入Transformer 架構開發多語客服系統，以提 升長篇金融文件的自動翻譯品質。下列何者為該模型能顯著改善翻譯 準確度的主要原因？", "options": { "A": "透過自注意力機制（Self-Attention Mechanism）捕捉長距離語 境依賴關係", "B": "透過卷積運算（Convolution Operation）加速訓練過程", "C": "透過強化學習（Reinforcement Learning）自動調整語句生成策 略", "D": "透過資料增強（Data Augmentation）平衡多語語料比例" }, "answer": "A", "topic": "NLP" },
  { "id": "s1q3", "subject": 1, "number": 3, "question": "某企業計畫應用BERT（Bidirectional Encoder Representations from Transformers）模型分析大量顧客意見，以強化客服自動回覆 系統。在BERT 的預訓練過程中，「遮罩語言模型（Masked Language Model, MLM）」的主要訓練策略為何？", "options": { "A": "依序遮罩句尾詞語，讓模型從左到右逐步生成完整句子", "B": "隨機遮罩部分詞語，並讓模型根據雙向上下文（Bidirectional Context）預測被遮罩的詞", "C": "透過對抗訓練（Adversarial Training）生成語意相似的擾動樣 本以提升泛化性", "D": "以未遮罩的詞為條件，使用解碼器（Decoder）結構重建整句內容" }, "answer": "B", "topic": "NLP" },
  { "id": "s1q4", "subject": 1, "number": 4, "question": "在詞向量（Word Embedding）訓練方法中，GloVe（Global Vectors for Word Representation）與Word2Vec 的主要差異為何？", "options": { "A": "Word2Vec 以詞頻權重訓練詞向量，而GloVe 以隨機初始化向量進 行學習", "B": "Word2Vec 以全局統計矩陣為基礎，而GloVe 採用神經網路進行上 下文預測", "C": "Word2Vec 為基於預測的模型，而GloVe 為基於共現統計的模型", "D": "Word2Vec 僅能用於靜態文本語料，而GloVe 可應用於即時語料更 新" }, "answer": "C", "topic": "NLP" },
  { "id": "s1q5", "subject": 1, "number": 5, "question": "某企業以詞頻–逆文件頻率（Term Frequency–Inverse Document Frequency, TF-IDF）方法分析顧客意見內容，但發現模型在處理篇 幅較長的回饋文本時，無法準確反映關鍵詞的重要性。下列何者為造 成此現象的主要原因？", "options": { "A": "長文本中的詞頻偏高，導致常見詞權重被過度放大", "B": "長文本中缺乏明確句子邊界，造成 TF-IDF 無法計算詞頻", "C": "TF-IDF 無法同時處理多份文件", "D": "長文本會改變IDF（Inverse Document Frequency）的計算，使所 有詞權重趨於相近" }, "answer": "A", "topic": "NLP" },
  { "id": "s1q6", "subject": 1, "number": 6, "question": "某企業嘗試以N-gram 語言模型（N-gram Language Model）建立客服 自動回覆系統，但發現模型生成的句子雖在片段上合理，卻缺乏整體 語意連貫性。此問題最可能源自N-gram 模型的哪一項限制？", "options": { "A": "N-gram 模型在訓練過程中需要龐大計算量，導致長句無法收斂", "B": "N-gram 模型僅根據固定長度的前序詞建立機率估計，難以捕捉長 距離依賴關係（Long-range Dependencies）", "C": "N-gram 模型缺乏語意嵌入（Semantic Embedding）層，因此無法 表徵詞語間的語意相似度", "D": "N-gram 模型假設詞與詞之間相互獨立，導致無法建構上下文語意 關聯" }, "answer": "B", "topic": "NLP" },
  { "id": "s1q7", "subject": 1, "number": 7, "question": "在企業導入的智慧監控系統中，模型以物件偵測（Object Detection）方式自動辨識影像中的人物與車輛。若評估指標採用平 均精確率（Mean Average Precision, mAP），其中 IoU （Intersection over Union）閾值設定較高時，代表下列哪一項意 義？", "options": { "A": "預測邊界框與真實邊界框的重疊程度越高，模型偵測結果越精 準", "B": "預測邊界框與真實邊界框的誤差越大，導致mAP 數值上升", "C": "模型整體精確率（Precision）降低，但召回率（Recall）上升", "D": "預測邊界框的評估結果不受真實框大小影響" }, "answer": "A", "topic": "CV" },
  { "id": "s1q8", "subject": 1, "number": 8, "question": "關於Softmax 與Max-Pooling，下列敘述何者正確？", "options": { "A": "Softmax 與Max-Pooling 都會將特徵張量壓縮為單一最大值", "B": "Max-Pooling 會對輸入進行機率分佈的轉換", "C": "Softmax 會保留所有輸入資訊，但以比例表示；Max-Pooling 只保 留區域最大值", "D": "Softmax 主要用於特徵降維，而Max-Pooling 用於分類輸出" }, "answer": "C", "topic": "DL基礎" },
  { "id": "s1q9", "subject": 1, "number": 9, "question": "某企業在訓練生成式AI 模型時，導入資料增強（Data Augmentation）技術以擴充訓練資料，但觀察到模型效能反而下降。 下列哪一項最可能的原因與對應改善策略最為正確？", "options": { "A": "增強樣本未經隨機初始化，導致模型梯度更新不穩定，應重新設 計訓練啟動流程", "B": "增強後資料的特徵分佈與原始資料不一致，影響模型的泛化能 力，應檢查並調整增強策略以維持語意一致性", "C": "增強樣本的比例過高，造成模型對特定資料產生偏好，應適度提 高增強比例並調整學習率", "D": "增強後資料的標註可信度下降，導致訓練訊號偏差，應以半監督 學習方式重新校正資料" }, "answer": "B", "topic": "GenAI" },
  { "id": "s1q10", "subject": 1, "number": 10, "question": "如果希望同時兼顧「精確率（Precision）」和「召回率（Recall）」， 下列哪一個指標可以作為綜合評估的標準？", "options": { "A": "準確率（Accuracy）", "B": "均方根誤差（RMSE）", "C": "均方誤差（MSE）", "D": "F1 分數（F1 Score）" }, "answer": "D", "topic": "評估" },
  { "id": "s1q-a1", "source": "authored", "subject": 1, "number": 1, "question": "某連鎖零售品牌規劃在門市部署一套 AI 顧客行為分析系統,管理層希望「先小範圍試,確認系統穩定且能收到有用回饋,再全國推開」。下列哪一個漸進式部署做法最符合此原則?", "options": { "A": "選擇全國各地 5% 的門市,涵蓋不同城市與商圈規模,以增加樣本多樣性", "B": "選定同一城市、相近商圈規模的 3 家旗艦店試行,集中觀察使用情況", "C": "在所有門市的後台啟用,但暫不開放給店員,只蒐集系統運行數據", "D": "從營業額最高的 10 家門市開始啟用,以最大化收益測試" }, "answer": "B", "topic": "AI風險" },
  { "id": "s1q-a2", "source": "authored", "subject": 1, "number": 2, "question": "某銀行客服中心打算上線 AI 客服機器人,主管提議「先在所有客服分機都裝,但設成『建議模式』(只給專員看建議,不直接回覆客戶)」。從漸進式部署原則來看,此做法最大的問題是什麼?", "options": { "A": "建議模式無法量測 AI 模型的延遲,影響後續效能評估", "B": "全範圍部署違反『風險可控』原則,出事時影響面太大", "C": "AI 沒有真正接觸客戶與處理對話,等於收不到實際使用回饋,無法迭代", "D": "建議模式增加專員工作負擔,可能導致他們抵制系統上線" }, "answer": "C", "topic": "AI風險" }
];
